# Generated by Django 5.2.8 on 2025-11-14 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='boardgames/')),
                ('rules', models.TextField(blank=True, help_text='Digite ou cole as regras aqui')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Foto do console', null=True, upload_to='consoles/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('platform_image', models.ImageField(blank=True, null=True, upload_to='platforms/')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('is_captured', models.BooleanField(default=False)),
                ('game_captured_in', models.CharField(blank=True, help_text='Ex: Red, Scarlet, etc.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonHallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(help_text='Ex: Pokémon Red (Zerado 1)', max_length=100)),
                ('sprite_1', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_2', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_3', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_4', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_5', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_6', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('genre', models.CharField(blank=True, help_text='Ex: RPG, Luta, etc.', max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, help_text='Ano de lançamento', null=True)),
                ('play_time', models.CharField(blank=True, help_text='Ex: 5h, 302h (opcional)', max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Nota de 0 a 10 (ex: 8.5)', max_digits=3, null=True)),
                ('observations', models.TextField(blank=True, help_text='DLCs, comentários, etc.', null=True)),
                ('status', models.CharField(choices=[('ZEREI', 'Zerei'), ('JOGUEI', 'Joguei'), ('JOGANDO', 'Jogando'), ('PAUSADO', 'Pausado')], default='JOGUEI', max_length=10)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.platform')),
                ('hall_of_fame_entry', models.ForeignKey(blank=True, help_text='Se for um jogo Pokémon zerado, linke a equipe aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemonhalloffame')),
            ],
        ),
    ]
