# Generated by Django 5.2.8 on 2025-11-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, help_text='Digite ou cole as regras aqui')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo_url', models.URLField(blank=True, help_text='Link para uma foto do console', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('is_captured', models.BooleanField(default=False)),
                ('game_captured_in', models.CharField(blank=True, help_text='Ex: Red, Scarlet, etc.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ZEREI', 'Zerei'), ('JOGUEI', 'Joguei'), ('JOGANDO', 'Jogando'), ('PAUSADO', 'Pausado')], default='JOGUEI', max_length=10)),
                ('is_completed', models.BooleanField(default=False, help_text='Marque se este jogo foi zerado')),
                ('my_review', models.TextField(blank=True, help_text='Escreva sua análise (só para zerados)', null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.console')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonHallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(help_text='Ex: Pokémon Red (Zerado 1)', max_length=100)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('team_members', models.ManyToManyField(to='api.pokemon')),
            ],
        ),
    ]
