# Generated by Django 5.2.8 on 2025-12-04 14:38

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('platform_image', models.ImageField(blank=True, null=True, upload_to='platforms/')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('shiny_sprite_url', models.URLField(blank=True, null=True)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='boardgames/')),
                ('rules', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_players', models.IntegerField(blank=True, null=True)),
                ('max_players', models.IntegerField(blank=True, null=True)),
                ('play_time', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='consoles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('api_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games_cover/')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_contributions', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.platform')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonHallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('sprite_1', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_2', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_3', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_4', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_5', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('sprite_6', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.avatar_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('favorite_game', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ZEREI', 'Zerei'), ('JOGUEI', 'Joguei'), ('JOGANDO', 'Jogando'), ('PAUSADO', 'Pausado'), ('QUERO', 'Quero Jogar'), ('PLATINEI', 'Platinei')], default='JOGUEI', max_length=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('play_time', models.CharField(blank=True, max_length=20, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by_users', to='api.gamecatalog')),
                ('hall_of_fame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemonhalloffame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_catalog')},
            },
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shiny', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pokemon', 'is_shiny')},
            },
        ),
    ]
