# Generated by Django 5.2.8 on 2025-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='console',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgames/'),
        ),
        migrations.AddField(
            model_name='console',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto do console', null=True, upload_to='consoles/'),
        ),
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
