# Generated by Django 5.2.8 on 2025-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boardgame_age_boardgame_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='game_captured_in',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='is_shiny_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='shiny_sprite_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
