# Generated by Django 5.2.9 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
