# Generated by Django 5.2.9 on 2025-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_profile_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_position',
            field=models.CharField(default='center', max_length=20),
        ),
    ]
