# Generated by Django 5.2.9 on 2025-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_avatar_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_position',
            field=models.CharField(default='50% 50%', max_length=50),
        ),
    ]
